### ISSUE TITLE
Item Pack won't open, contains duplicates of everything?

### ISSUE THREAD

**Issue by GambetTV** [TheInvaderZim/night-city-gang-and-corp-mook-pack#2]
Hey there, I'm using v2 of your mook pack on Foundry v11.315 and Cyberpunk Red 0.88.2. I notice I can't open the Item Pack compendium at all. The other two compendiums open fine, though. I was able to Import the Item Pack without opening the compendium, but when I did it created two of every item. As far as I can tell these duplicates are completely identical, and so I assume this is a bug.

**Comment by TheInvaderZim** [comment]
Appreciate you raising the issue - it's a known bug. I have no idea what exactly caused it (item compendiums were just kinda wonky for awhile via Foundry, I think), but fortunately, it seems to have resolved itself lately, and the compendium should be properly functional with the next release. Probably.

Thanks again for letting me know!
